---
# keyboard firmware
include:
  - board: zitaotech_keypoint_left
    shield: lpm_view;left_bbtrackpad_keypoint;raw_hid_adapter

  - board: zitaotech_keypoint_right
    shield: lpm_view;right_trackpoint_keypoint


# rest firmware
#  - board: zitaotech_keypoint_left
#    shield: lpm_view;left_bbtrackpad_keypoint;raw_hid_adapter;settings_reset
#  - board: zitaotech_keypoint_right
#    shield: lpm_view;right_trackpoint_keypoint;settings_reset
