# I2C Trackpad
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_I2C_NRFX=y
CONFIG_LOG=y

# Raw HID for vibe coding status
CONFIG_RAW_HID=y

# Log via USB or Segger RTT
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000
